# Generated by host/gen_render.py -- do not edit.
# Lookup tables for the LED renderer (only included when render = 1).
.data
# render_color[cubie*3 + j]: 24-bit colour of home sticker j of a cubie
# (cubie 0..6 as in state_perm, cubie 7 = the fixed corner).
render_color:
    .word 0x0000FF, 0xFF0000, 0xFFFFFF
    .word 0x00FF00, 0xFFFFFF, 0xFF0000
    .word 0x00FF00, 0xFF0000, 0xFFFF00
    .word 0x0000FF, 0xFFFFFF, 0xFF8000
    .word 0x00FF00, 0xFF8000, 0xFFFFFF
    .word 0x00FF00, 0xFFFF00, 0xFF8000
    .word 0x0000FF, 0xFF8000, 0xFFFF00
    .word 0x0000FF, 0xFFFF00, 0xFF0000
# render_offset[pos*3 + k]: byte offset from LED_MATRIX_0_BASE of the
# top-left pixel of the facelet at position pos, slot k (pos 7 = fixed).
render_offset:
    .half 508, 1068, 1088
    .half 2048, 1508, 1488
    .half 2032, 1472, 1452
    .half 88, 1104, 980
    .half 2468, 1400, 1524
    .half 2452, 1436, 1416
    .half 72, 996, 1016
    .half 492, 1032, 1052
# source / twist tables of solver.c, one 7-byte row per face (R, B, D).
render_source:
    .byte 1, 4, 2, 0, 3, 5, 6
    .byte 0, 1, 2, 4, 5, 6, 3
    .byte 0, 2, 5, 3, 1, 4, 6
render_twist:
    .byte 1, 2, 0, 2, 1, 0, 0
    .byte 0, 0, 0, 1, 2, 1, 2
    .byte 0, 0, 0, 0, 0, 0, 0
