#!/usr/bin/env python3
"""Host-side generator for the LED renderer's lookup tables (asm/render_tables.s).

Geometry: x: L=-1, R=+1; y: D=-1, U=+1; z: B=-1, F=+1.
Array index 0..6 = UFR, DFR, DFL, UBR, DBR, DBL, UBL (minirubik README);
index 7 = the fixed corner UFL.
Sticker slot k of a position = k counter-clockwise steps (seen from outside
the corner) away from its U/D face.  A cubie c with orientation o shows its
home sticker j at slot (j + o) mod 3, so  colour(slot k) = home[c][(k - o) mod 3].
The script checks this model against a geometric simulation of R, B, D.
"""
import random, sys

W, H = 35, 25
FW, FH = 4, 3            # pixels per facelet
Y0 = 0                    # first matrix row used by the net
POS = [(1,1,1),(1,-1,1),(-1,-1,1),(1,1,-1),(1,-1,-1),(-1,-1,-1),(-1,1,-1),(-1,1,1)]
SOURCE = [[1,4,2,0,3,5,6],[0,1,2,4,5,6,3],[0,2,5,3,1,4,6]]
TWIST  = [[1,2,0,2,1,0,0],[0,0,0,1,2,1,2],[0,0,0,0,0,0,0]]
COLOR = {'U':0x0000FF,'D':0x00FF00,'F':0xFF0000,'B':0xFF8000,'R':0xFFFFFF,'L':0xFFFF00}
SLOT  = {'B':(0,1),'L':(1,1),'F':(2,1),'R':(3,1),'U':(2,0),'D':(2,2)}  # net: B L F R, U/D on F

def face_of(axis, sign):
    return {(0,1):'R',(0,-1):'L',(1,1):'U',(1,-1):'D',(2,1):'F',(2,-1):'B'}[(axis,sign)]

def slots(pos):
    """Axes of the three stickers of a corner, counter-clockwise from U/D."""
    x,y,z = pos
    return [1,2,0] if x*y*z > 0 else [1,0,2]

def cell(pos, axis):
    """(column,row) of the facelet inside its 2x2 face on the net."""
    x,y,z = [(v+1)//2 for v in pos]
    f = face_of(axis, pos[axis])
    return {'F':(x,1-y),'R':(1-z,1-y),'L':(z,1-y),'B':(1-x,1-y),'U':(x,z),'D':(x,1-z)}[f]

def pixel(pos, axis):
    f = face_of(axis, pos[axis]); s = SLOT[f]; c = cell(pos, axis)
    return s[0]*(2*FW+1) + c[0]*FW, Y0 + s[1]*(2*FH+1) + c[1]*FH

def home(c, j):
    p = POS[c]; a = slots(p)[j]
    return face_of(a, p[a])

def facelets(p, o):
    """dict (pos index, slot) -> face letter, from the cubie-level state."""
    out = {}
    pp = list(p)+[7]; oo = list(o)+[0]
    for i in range(8):
        for k in range(3):
            out[(i,k)] = home(pp[i], (k-oo[i]) % 3)
    return out

def quarter(p, o, face):
    return ([p[SOURCE[face][i]] for i in range(7)],
            [(o[SOURCE[face][i]] + TWIST[face][i]) % 3 for i in range(7)])

# ---- independent geometric model -------------------------------------
def rot(face, v):
    x,y,z = v
    if face == 0: return (x, z, -y)     # R clockwise seen from +x
    if face == 1: return (-y, x, z)     # B clockwise seen from -z
    return (z, y, -x)                   # D clockwise seen from -y
def in_layer(face, pos):
    return [pos[0]==1, pos[2]==-1, pos[1]==-1][face]
def geo_solved():
    g = {}
    for pos in POS:
        for a in range(3):
            n = [0,0,0]; n[a] = pos[a]
            g[(pos,tuple(n))] = face_of(a,pos[a])
    return g
def geo_turn(g, face):
    return {((rot(face,p),rot(face,n)) if in_layer(face,p) else (p,n)):c for (p,n),c in g.items()}
def geo_facelets(g):
    out = {}
    for i,pos in enumerate(POS):
        for k,a in enumerate(slots(pos)):
            n = [0,0,0]; n[a] = pos[a]
            out[(i,k)] = g[(pos,tuple(n))]
    return out

def selfcheck():
    random.seed(1)
    for _ in range(2000):
        p, o, g = list(range(7)), [0]*7, geo_solved()
        for _ in range(random.randint(0,20)):
            f = random.randrange(3)
            p, o = quarter(p, o, f); g = geo_turn(g, f)
        assert facelets(p,o) == geo_facelets(g), "model mismatch"
    print("self-check passed: cubie model == geometric model (2000 random walks)", file=sys.stderr)

def ascii_net(p, o):
    grid = [[' ']*W for _ in range(Y0+20)]
    fl = facelets(p,o)
    for i,pos in enumerate(POS):
        for k,a in enumerate(slots(pos)):
            x,y = pixel(pos,a)
            for dy in range(FH):
                for dx in range(FW):
                    grid[y+dy][x+dx] = fl[(i,k)]
    return '\n'.join(''.join(r) for r in grid)

def parse(s):
    return [int(ch)-1 for ch in s[:7]], [int(ch)-1 for ch in s[7:]]

def emit():
    L = ["# Generated by host/gen_render.py -- do not edit.",
         "# Lookup tables for the LED renderer (only included when render = 1).",
         ".data",
         "# render_color[cubie*3 + j]: 24-bit colour of home sticker j of a cubie",
         "# (cubie 0..6 as in state_perm, cubie 7 = the fixed corner).",
         "render_color:"]
    for c in range(8):
        L.append("    .word " + ", ".join("0x%06X" % COLOR[home(c,j)] for j in range(3)))
    L += ["# render_offset[pos*3 + k]: byte offset from LED_MATRIX_0_BASE of the",
          "# top-left pixel of the facelet at position pos, slot k (pos 7 = fixed).",
          "render_offset:"]
    for i,pos in enumerate(POS):
        offs = []
        for a in slots(pos):
            x,y = pixel(pos,a); offs.append(str((y*W+x)*4))
        L.append("    .half " + ", ".join(offs))
    L += ["# source / twist tables of solver.c, one 7-byte row per face (R, B, D).",
          "render_source:"]
    L += ["    .byte " + ", ".join(map(str,r)) for r in SOURCE]
    L += ["render_twist:"]
    L += ["    .byte " + ", ".join(map(str,r)) for r in TWIST]
    return "\n".join(L) + "\n"

if __name__ == "__main__":
    selfcheck()
    if len(sys.argv) > 1:            # print the expected picture of a state
        p,o = parse(sys.argv[1])
        for mv in sys.argv[2:]:
            f = "RBD".index(mv[0]); n = {"":1,"2":2,"'":3}[mv[1:]]
            for _ in range(n): p,o = quarter(p,o,f)
        print(ascii_net(p,o))
    else:
        sys.stdout.write(emit())
